version: "3.9"

services:
  odds_scraper:
    build:
      context: ./odds_scraper
    container_name: odds_scraper
    command: npm start

  results_scraper:
    build:
      context: ./results_scraper
    container_name: results_scraper
    command: npm start

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
